FROM	frrouting/frr:latest

COPY    ../P2/Makefile /Makefile
COPY    ../P2/router.sh /ipconfig.sh

#       INSTALL MAKE
RUN     apk add make
#       CONFIGURE FRR
RUN     sed -i 's/^bgpd=no$/bgpd=yes/' /etc/frr/daemons && \
        sed -i 's/^ospfd=no$/ospfd=yes/' /etc/frr/daemons && \
        sed -i 's/^isisd=no$/isisd=yes/' /etc/frr/daemons 
